name: update-yart

on: 
  schedule:
    - cron: '30 2 * * *'

  workflow_dispatch:

env:
  IMAGE_NAME: yart

jobs:
  commented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: update
        run: |
          git config user.name github-bot
          git config user.email "<>"

          npm outdated --json > _v.json || true

          function update {
            local NAME=$1
            node -e "
            const fs = require('fs')
            const version = JSON.parse(fs.readFileSync('./_v.json', 'utf-8'))
            const dep = version['$NAME']
            if(dep && dep.current !== dep.latest) { 
            const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf-8'))
            pkg.devDependencies['$NAME'] = dep.latest
            fs.writeFileSync('./package.json', JSON.stringify(pkg, undefined, 2), 'utf-8')
            }
            "
          }

          update yart-cli
          update yart-dev-server

          rm _v.json
          
          yarn

          git add .
          git commit -m "note:update version" || true
          git push origin master || true
          docker build . --file dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
