name: update-yart

on: 
  schedule:
    - cron: '30 2 * * *'

  workflow_dispatch:

jobs:
  commented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: update
        run: |
          git config user.name github-bot
          git config user.email "<>"

          npm outdated --json > _v.json || true

          function update {
            local NAME=$1
            node -e "
            const fs = require('fs')
            const version = JSON.parse(fs.readFileSync('./_v.json', 'utf-8'))
            const dep = version['$NAME']
            if(dep && dep.current !== dep.latest) { 
            const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf-8'))
            pkg.dependencies['$NAME'] = '$TARGET_VERSION'
            fs.writeFileSync('./package.json', JSON.stringify(pkg, undefined, 2), 'utf-8')
            }
            "
          }

          update yart-cli
          update yart-dev-server

          rm _v.json
          
          yarn

          git add .
          git commit -m "note:update version" || true
          git push origin master || true
